export const routes = {
    homePage: '/',
    login: '/login',
    register: '/register',
    dashboard: '/dashboard-Page',
    orderPage: '/order-Page',
    feedbackPage: '/fb-Page',
    accountPage: '/account-Page',
    productPage: '/product-Page',
    revenuePage: '/revenue-Page',
    engagementRings: '/engagement-rings',
    shoppingCart: '/shopping-cart',
    userInfo: '/userinfo/*',
    detail: '/product-detail',
    checkout: '/checkout',  
    checkoutcomplete: '/checkout-complete',
    staffsite : '/staffSite',
    history : '/history',
    wishList: '/wish-list',
    ringSize: '/ring-size-guide',
    diamond: '/diamond',
    necklace:'/necklace'
}